services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "waC14CJj"
      - key: DATABASE_URL
        fromDatabase: "postgresql://fardeen_41eo_user:a0RRh5bqVobZJv0zcjptHqjpPenIdM5w@dpg-d1ln5kqdbo4c73a4l21g-a.oregon-postgres.render.com/fardeen_41eo"
          name: my-database
          property: connectionString
